export const initialQuests = [
  {
    id: 1,
    title: '자신의 하루활동 기록하기',
    description: '오늘 하루 무엇을 했는지 간단하게 남겨보세요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 2,
    title: '자신의 감정 기록하기',
    description: '기쁨, 슬픔, 불안함 등 어떤 감정이든 솔직하게 적어봐요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 3,
    title: '정해진 시간에 잠자리에 들고 일어나는 시간을 기록하기',
    description: '규칙적인 수면 패턴은 좋은 컨디션의 첫걸음이에요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 4,
    title: '하루 2~3끼 규칙적으로 식사 시 체크하기',
    description: '몸에 좋은 에너지를 꾸준히 채워주는 것이 중요해요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 5,
    title: '5분간 타이머를 재고 명상하기',
    description: '복잡한 생각을 잠시 멈추고 현재에 집중해보세요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 6,
    title: '스트레칭 영상 보고 10분간 운동하기',
    description: '가볍게 몸을 움직이며 굳어있던 근육을 풀어주세요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 7,
    title: '근처 상담 센터 및 온라인 상담 센터 알려주기',
    description: '도움이 필요할 때 기댈 수 있는 곳들을 알아봐요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 8,
    title: '캐릭터에게 칭찬하기',
    description: '긍정적인 말을 건네며 나와 캐릭터 모두에게 힘을 주세요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 9,
    title: '스스로 목표 설정하게 하기',
    description: '크고 작은 목표를 세우고 성취감을 느껴보세요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 10,
    title: '은둔하다가 다시 사회로 돌아온 사람의 후기 듣기',
    description: '나와 비슷한 경험을 한 사람의 이야기에서 용기를 얻어요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 11,
    title: '관심있는 커뮤니티 찾아보기',
    description: '나의 취미나 관심사를 공유할 수 있는 온라인 공간을 탐색해보세요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 12,
    title: '가족에게 메시지 보내기',
    description: '화면에 추천된 문장으로 따뜻한 안부를 전해보세요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 13,
    title: '온라인 익명 게시판에 글 남기기',
    description: '부담 없이 당신의 생각이나 질문을 자유롭게 적어보세요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 14,
    title: '비대면 독서/취미 모임 참여 탐색하기',
    description: '집에서 편안하게 새로운 사람들과 교류를 시작해봐요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 15,
    title: '긍정적인 온라인 댓글 달기',
    description: '칭찬이나 공감의 표현으로 온라인 공간에 온기를 더해주세요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 16,
    title: '캐릭터와 교류하기',
    description: '캐릭터와 대화하며 즐거운 상호작용을 경험해보세요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 17,
    title: '짧은 전화나 대화 시도하기',
    description: '식당에 음식을 주문하는 것처럼 간단한 대화부터 시작해요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 18,
    title: '사회 불안과 관련된 영상 보여주기',
    description: '나만 겪는 어려움이 아니라는 것을 이해하고 위로받아요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 19,
    title: '챗봇과 대화하기',
    description: '어떤 이야기든 들어줄 준비가 된 챗봇과 대화를 나눠보세요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 20,
    title: '매일 감사한 일 3가지를 작성하기',
    description: '사소한 것에서 행복을 발견하는 연습을 해보세요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 21,
    title: '지역 커뮤니티 활동 탐색 및 참여하기',
    description: '우리 동네의 소모임이나 원데이 클래스를 찾아볼까요?',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 22,
    title: '지인/친구에게 먼저 연락하기',
    description: '간단한 안부 인사로 다시 연결되는 따뜻함을 느껴보세요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 23,
    title: '공공장소에서 짧은 대화 시도',
    description: '물건 값을 계산하며 "감사합니다"라고 말하는 것부터 시작해요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 24,
    title: '비대면 모임에서 대면 모임으로 전환 시도',
    description: '온라인에서 편해진 사람들과 오프라인 만남을 추진해봐요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 25,
    title: '관심 분야의 단기간 오프라인 강좌/워크숍 수강',
    description: '공통의 관심사를 가진 사람들과 자연스럽게 어울려봐요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 26,
    title: '캐릭터를 통해 사회불안 상황 시뮬레이션 및 대처 연습',
    description: '어려운 상황을 미리 연습하며 자신감을 키울 수 있어요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 27,
    title: '캐릭터와 긍정적 피드백 주고받기 연습',
    description: '칭찬을 주고받으며 긍정적인 상호작용에 익숙해져요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 28,
    title: '갈등 상황에 대한 이해 및 초기 대처법 학습',
    description: '모든 관계에는 갈등이 있어요. 건강하게 대처하는 법을 배워봐요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 29,
    title: '야외 활동/산책 그룹 참여',
    description: '함께 걸으며 자연스럽게 대화하는 편안함을 느껴보세요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 30,
    title: '자신의 강점과 약점 파악 및 활용',
    description: '나를 더 깊이 이해하고 나의 가능성을 발견하는 시간이에요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 31,
    title: '교육/직업 탐색 및 준비하기',
    description: '나의 미래를 위한 다양한 길을 탐색하고 정보를 모아보세요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 32,
    title: '일주일 예산 계획 및 사용 내역 기록하기',
    description: '스스로 돈을 관리하며 계획적인 소비 습관을 길러봐요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 33,
    title: '전체적인 집 대청소하기',
    description: '공간을 정리하며 마음까지 상쾌해지는 변화를 느껴보세요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 34,
    title: '캐릭터와 깊은 대화 스킬 늘리기',
    description: '단순한 대화를 넘어, 서로의 생각을 공유하는 연습을 해요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 35,
    title: '스트레스 및 시간 관리 방법 계획 짜보기',
    description: '나만의 스트레스 해소법을 찾고 하루를 효율적으로 계획해보세요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 36,
    title: '사회적인 뉴스에 대해서 의견 작성해보기',
    description: '세상 돌아가는 소식에 관심을 갖고 나의 생각을 정리해봐요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 37,
    title: '캐릭터와 심각한 갈등 상황 해결해보기',
    description: '가상의 갈등 해결을 통해 실제 상황 대처 능력을 키워요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 38,
    title: '새로운 취미를 배우고 다른 사람과 나눠보기',
    description: '새로운 활동으로 삶의 활력을 더하고 사람들과 공유해보세요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 39,
    title: '캐릭터에게 긍정적인 대화 던져주기',
    description: '먼저 긍정적인 말을 건네며 대화의 분위기를 이끌어보세요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 40,
    title: '주도적으로 소규모 모임/활동 계획 및 실행해보기',
    description: '직접 모임을 계획하고 리더십을 발휘하는 경험을 해보세요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 41,
    title: '진로 탐색 및 직업 성향 검사하기',
    description: '객관적인 검사를 통해 나에게 맞는 일이 무엇일지 알아봐요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 42,
    title: '이력서/자기소개서 초안 작성',
    description: '나의 경험과 장점을 글로 정리하며 자신을 되돌아보는 시간이에요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 43,
    title: '채용 공고 탐색 및 지원하기',
    description: '관심 있는 분야의 채용 공고를 찾아보고 지원하는 용기를 내보세요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 44,
    title: '캐릭터를 통한 모의 면접 혹은 실제로 대면 모의 면접',
    description: '실전처럼 연습하며 면접에 대한 긴장감을 줄여나가요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 45,
    title: '직장 내 기본 커뮤니케이션 학습 (AI 챗봇)',
    description: '챗봇과 함께 이메일 작성, 보고 등 기본적인 업무 소통을 배워봐요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 46,
    title: '직무 역량 강화 영상 보여주기',
    description: '나의 전문성을 키울 수 있는 유용한 영상들을 시청해보세요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 47,
    title: '멘토를 연결시켜 현직에서 일하는 경험 공유 받기',
    description: '현직자의 생생한 조언을 통해 현실적인 계획을 세울 수 있어요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 48,
    title: '스트레스 관리 방법 동영상 시청하기',
    description: '건강하게 스트레스를 해소하는 나만의 방법을 찾아보세요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 49,
    title: '사회보험 및 노동권리 학습하기',
    description: '사회초년생으로서 알아야 할 필수 권리를 미리 배워둬요.',
    steps: 1,
    isCompleted: false,
  },
  {
    id: 50,
    title: '첫번째로 일한 날 소감 적어보기',
    description: '새로운 사회에서의 첫걸음을 축하해요. 벅찬 감정을 기록해보세요.',
    steps: 1,
    isCompleted: false,
  },
];
  // 대단계 레벨업에 필요한 총 칸 수
  export const STEPS_PER_MAJOR_LEVEL = 10;